# models/marts/dim/schema.yml

version: 2

models:
  - name: dim_aisle
    description: "Dimensi rak tempat produk"
    columns:
      - name: aisle_id
        description: "ID unik untuk setiap rak (aisle)"
        tests:
          - not_null
          - unique
      - name: aisle_name
        description: "Nama rak"
  
  - name: dim_department
    description: 'Dimensi kategori produk'
    columns:
      - name: department_id
        description: 'ID unik untuk setiap department (kategori)'
        tests: 
          - not_null
          - unique
      - name: department_name
        description: 'Nama Kategori'


  - name : dim_product
    description: "Dimensi produk lengkap dengan referensi aisle dan department"
    columns: 
      - name: product_id
        description: 'ID unik untuk setiap produk'
        tests:
          - not_null
          - unique
      - name: product_name 
        description: 'Nama Produk'
      - name: aisle_id
        description: 'foreign key ke dim_aisle'
        tests:
          - not_null
          - relationships:
              to: ref('dim_aisle')
              field: aisle_id
      - name: department_id
        description: 'foreign key ke dim_department'
        tests:
          - not_null
          - relationships:
              to: ref('dim_department')
              field: department_id

  - name: dim_user
    description: >
      Dimensi pelanggan yang menyimpan metrik ringkasan perilaku belanja:
      jumlah order, jeda antar order, dan informasi order terakhir.

    columns:
      - name: user_id
        description: "ID unik pelanggan"
        tests: [not_null, unique]

      - name: total_orders
        description: "Total jumlah order yang dilakukan oleh user"
        tests: [not_null]

      - name: avg_days_between_orders
        description: "Rata-rata jeda hari antar order"
        tests: []

      - name: last_order_number
        description: "Nomor urut order terakhir"
        tests: []

      - name: days_since_last_order
        description: "Jumlah hari sejak order terakhir (diambil dari kolom days_gap)"
        tests: []

  - name: dim_order
    description: >
      Dimensi order yang menyimpan informasi urutan pembelian oleh user,
      termasuk hari, jam, dan jeda antar order.

    columns:
      - name: order_id
        description: "Primary key dari order (unik per transaksi)"
        tests: [not_null, unique]

      - name: user_id
        description: "User yang melakukan order"
        tests: [not_null]

      - name: order_number
        description: "Urutan keberapa order dilakukan oleh user"
        tests: [not_null]

      - name: order_day
        description: "Hari dalam minggu saat order dilakukan (Sunday–Saturday)"
        tests: [not_null]

      - name: order_hour
        description: "Jam saat order dilakukan (0–23)"
        tests: [not_null]

      - name: order_days_gap
        description: >
          Jeda hari sejak order sebelumnya. NULL jika ini adalah order pertama user.
        tests: []

  - name: dim_time
    description: >
      Dimensi waktu berdasarkan kombinasi hari dalam minggu dan jam order.
      Digunakan untuk analisis perilaku pelanggan berdasarkan waktu.

    columns:
      - name: time_id
        description: "Surrogate key unik untuk kombinasi day_of_week dan hour_of_day"
        tests: [not_null, unique]

      - name: day_of_week
        description: "Hari dalam minggu saat order dilakukan (Sunday–Saturday)"
        tests: [not_null]

      - name: hour_of_day
        description: "Jam dalam hari saat order dilakukan (0–23)"
        tests: [not_null]
