version: 2

models:
  - name: fact_order_items
    description: >
      Tabel fakta granular yang merepresentasikan setiap item produk dalam order.
      Setiap baris mewakili satu produk yang dibeli dalam satu order oleh user,
      serta direferensikan ke dimensi user, product, order, dan time.

    columns:
      - name: user_id
        description: "Foreign key ke dim_user. Mengidentifikasi siapa yang melakukan order."
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_id

      - name: order_id
        description: "Foreign key ke dim_order. Merepresentasikan order utama."
        tests:
          - not_null
          - relationships:
              to: ref('dim_order')
              field: order_id

      - name: product_id
        description: "Foreign key ke dim_product. Menunjukkan produk yang dibeli dalam order."
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: time_id
        description: >
          Foreign key ke dim_time. Menggabungkan informasi waktu berdasarkan hari dan jam order.
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id

      - name: order_number
        description: >
          Urutan keberapa user tersebut melakukan order (dalam sejarah belanjanya).
        tests:
          - not_null

      - name: days_since_prior_order
        description: >
          Jumlah hari sejak order sebelumnya dari user yang sama.
          NULL berarti ini adalah order pertama.

      - name: add_to_cart_order
        description: >
          Urutan produk ini dimasukkan ke dalam keranjang pada saat checkout.
        tests:
          - not_null

      - name: reordered
        description: >
          Apakah produk ini merupakan pembelian ulang (1 = iya, 0 = tidak).
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
