version: 2

models:
- name: fact_order_items
  description: >
    Tabel fakta granular transaksi, dibentuk dari join antar dimensi 
    (dim_order, dim_product, dim_time, dan dim_user secara tidak langsung melalui dim_order).

  columns:
    - name: user_id
      description: "ID user yang melakukan order (diturunkan dari dim_order)"
      tests:
        - not_null

    - name: order_id
      description: "ID unik order, foreign key ke dim_order"
      tests:
        - not_null
        - relationships:
            to: ref('dim_order')
            field: order_id

    - name: product_id
      description: "Produk dalam order, foreign key ke dim_product"
      tests:
        - not_null
        - relationships:
            to: ref('dim_product')
            field: product_id

    - name: time_id
      description: "Waktu order, foreign key ke dim_time (optional)"
      tests:
        - relationships:
            to: ref('dim_time')
            field: time_id

    - name: order_number
      description: "Urutan order keberapa oleh user tersebut"
      tests:
        - not_null

    - name: days_gap
      description: "Jeda (dalam hari) dari order sebelumnya. NULL jika order pertama."
      tests: []

    - name: add_to_cart_order
      description: "Urutan produk dimasukkan ke dalam keranjang saat order"
      tests: []

    - name: reordered
      description: "Apakah produk dibeli ulang (1 = ya, 0 = tidak)"
      tests:
        - accepted_values:
            values: [0, 1]
